import type { Metadata } from 'next';
import './globals.css';
import Nav from '@/components/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen w-sceeen justify-center flex items-center">
          <main className="flex min-h-screen flex-col items-center gap-8 p-24">
            <Nav />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
